FactoryGirl.define do
  factory :raw_stats, class: LolClient::RawStats do
    assists { (1..10).to_a.sample }
    barracks_killed { (1..10).to_a.sample }
    champions_killed { (1..10).to_a.sample }
    combat_player_score { (1..10).to_a.sample }
    consumables_purchased { (1..10).to_a.sample }
    damage_dealt_player { (1..10).to_a.sample }
    double_kills { (1..10).to_a.sample }
    first_blood { (1..10).to_a.sample }
    gold { (1..10).to_a.sample }
    gold_earned { (1..10).to_a.sample }
    gold_spent { (1..10).to_a.sample }
    item0 { (1..10).to_a.sample }
    item1 { (1..10).to_a.sample }
    item2 { (1..10).to_a.sample }
    item3 { (1..10).to_a.sample }
    item4 { (1..10).to_a.sample }
    item5 { (1..10).to_a.sample }
    item6 { (1..10).to_a.sample }
    items_purchased { (1..10).to_a.sample }
    killing_sprees { (1..10).to_a.sample }
    largest_critical_strike { (1..10).to_a.sample }
    largest_killing_spree { (1..10).to_a.sample }
    largest_multi_kill { (1..10).to_a.sample }
    legendary_items_created { (1..10).to_a.sample }
    level { (1..10).to_a.sample }
    magic_damage_dealt_player { (1..10).to_a.sample }
    magic_damage_dealt_to_champions { (1..10).to_a.sample }
    magic_damage_taken { (1..10).to_a.sample }
    minions_denied { (1..10).to_a.sample }
    minions_killed { (1..10).to_a.sample }
    neutral_minions_killed { (1..10).to_a.sample }
    neutral_minions_killed_enemy_jungle { (1..10).to_a.sample }
    neutral_minions_killed_your_jungle { (1..10).to_a.sample }
    node_capture { (1..10).to_a.sample }
    node_capture_assist { (1..10).to_a.sample }
    node_neutralize { (1..10).to_a.sample }
    node_neutralize_assist { (1..10).to_a.sample }
    num_deaths { (1..10).to_a.sample }
    num_items_bought { (1..10).to_a.sample }
    objective_player_score { (1..10).to_a.sample }
    penta_kills { (1..10).to_a.sample }
    physical_damage_dealt_player { (1..10).to_a.sample }
    physical_damage_dealt_to_champions { (1..10).to_a.sample }
    physical_damage_taken { (1..10).to_a.sample }
    quadra_kills { (1..10).to_a.sample }
    sight_wards_bought { (1..10).to_a.sample }
    spell1_cast { (1..10).to_a.sample }
    spell2_cast { (1..10).to_a.sample }
    spell3_cast { (1..10).to_a.sample }
    spell4_cast { (1..10).to_a.sample }
    summon_spell1_cast { (1..10).to_a.sample }
    summon_spell2_cast { (1..10).to_a.sample }
    super_monster_killed { (1..10).to_a.sample }
    team { (1..10).to_a.sample }
    team_objective { (1..10).to_a.sample }
    time_played { (1..10).to_a.sample }
    total_damage_dealt { (1..10).to_a.sample }
    total_damage_dealt_to_champions { (1..10).to_a.sample }
    total_damage_taken { (1..10).to_a.sample }
    total_heal { (1..10).to_a.sample }
    total_player_score { (1..10).to_a.sample }
    total_score_rank { (1..10).to_a.sample }
    total_time_crowd_control_dealt { (1..10).to_a.sample }
    total_units_healed { (1..10).to_a.sample }
    triple_kills { (1..10).to_a.sample }
    true_damage_dealt_player { (1..10).to_a.sample }
    true_damage_dealt_to_champions { (1..10).to_a.sample }
    true_damage_taken { (1..10).to_a.sample }
    turrets_killed { (1..10).to_a.sample }
    unreal_kills { (1..10).to_a.sample }
    victory_point_total { (1..10).to_a.sample }
    vision_wards_bought { (1..10).to_a.sample }
    ward_killed { (1..10).to_a.sample }
    ward_placed { (1..10).to_a.sample }
    nexus_killed { [true, false].sample }
    win { [true, false].sample }
  end
end
